.TH "CAboutDlg" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAboutDlg \- 
.SH SYNOPSIS
.br
.PP
.PP
CDialog를(을) 상속했습니다\&.
.SS "Public 타입"

.in +1c
.ti -1c
.RI "enum { \fBIDD\fP = IDD_ABOUTBOX }"
.br
.in -1c
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCAboutDlg\fP ()"
.br
.in -1c
.SS "Protected 멤버 함수"

.in +1c
.ti -1c
.RI "virtual void \fBDoDataExchange\fP (CDataExchange *pDX)"
.br
.in -1c
.SH "상세한 설명"
.PP 
robot society betaDlg\&.cpp 파일의 23 번째 라인에서 정의되었습니다\&.
.SH "멤버 열거형 문서화"
.PP 
.SS "anonymous enum"

.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIIDD \fP\fP
.PP
robot society betaDlg\&.cpp 파일의 29 번째 라인에서 정의되었습니다\&.
.PP
.nf
29 { IDD = IDD_ABOUTBOX };
.fi
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "CAboutDlg::CAboutDlg ()"

.PP
robot society betaDlg\&.cpp 파일의 39 번째 라인에서 정의되었습니다\&.
.PP
.nf
39                      : CDialog(CAboutDlg::IDD)
40 {
41 }
.fi
.SH "멤버 함수 문서화"
.PP 
.SS "void CAboutDlg::DoDataExchange (CDataExchange * pDX)\fC [protected]\fP, \fC [virtual]\fP"

.PP
robot society betaDlg\&.cpp 파일의 43 번째 라인에서 정의되었습니다\&.
.PP
.nf
44 {
45     CDialog::DoDataExchange(pDX);
46 }
.fi


.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
