.TH "CHARACTOR" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHARACTOR \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robot object\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "unsigned char \fBlevel\fP"
.br
.ti -1c
.RI "unsigned char \fBmain\fP"
.br
.ti -1c
.RI "unsigned char \fBsub\fP"
.br
.ti -1c
.RI "unsigned char \fBetc\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
robot object\&.h 파일의 40 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이타 문서화"
.PP 
.SS "unsigned char CHARACTOR::etc"

.PP
robot object\&.h 파일의 46 번째 라인에서 정의되었습니다\&.
.SS "unsigned char CHARACTOR::level"

.PP
robot object\&.h 파일의 43 번째 라인에서 정의되었습니다\&.
.SS "unsigned char CHARACTOR::main"

.PP
robot object\&.h 파일의 44 번째 라인에서 정의되었습니다\&.
.SS "unsigned char CHARACTOR::sub"

.PP
robot object\&.h 파일의 45 번째 라인에서 정의되었습니다\&.
.SS "unsigned char CHARACTOR::type"

.PP
robot object\&.h 파일의 42 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
