.TH "CIni" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CIni \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ini\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCIni\fP (const char *fileName)"
.br
.ti -1c
.RI "virtual \fB~CIni\fP ()"
.br
.ti -1c
.RI "void \fBLoadString\fP (const char *keyName, char *returnedString, \fBDWORD\fP nSize, char *defaultValue='')"
.br
.ti -1c
.RI "int \fBLoadInt\fP (const char *keyName, int defaultValue=0)"
.br
.ti -1c
.RI "float \fBLoadFloat\fP (const char *keyName, float defaultValue=0\&.0)"
.br
.ti -1c
.RI "void \fBSaveString\fP (const char *keyName, char *strData)"
.br
.ti -1c
.RI "void \fBSaveInt\fP (const char *keyName, int intData)"
.br
.ti -1c
.RI "void \fBSaveFloat\fP (const char *keyName, float floatData)"
.br
.ti -1c
.RI "void \fBTransfer\fP (bool bSave, const char *keyName, char *strData, \fBDWORD\fP nSize, char *defaultData='')"
.br
.ti -1c
.RI "void \fBTransfer\fP (bool bSave, const char *keyName, bool &boolData, bool defaultData=false)"
.br
.ti -1c
.RI "void \fBTransfer\fP (bool bSave, const char *keyName, int &intData, int defaultData=0)"
.br
.ti -1c
.RI "void \fBTransfer\fP (bool bSave, const char *keyName, long &longData, long defaultData=0)"
.br
.ti -1c
.RI "void \fBTransfer\fP (bool bSave, const char *keyName, \fBDWORD\fP &dwordData, \fBDWORD\fP defaultData=0)"
.br
.ti -1c
.RI "void \fBTransfer\fP (bool bSave, const char *keyName, float &floatData, float defaultData=0\&.0f)"
.br
.ti -1c
.RI "void \fBTransfer\fP (bool bSave, const char *keyName, double &doubleData, double defaultData=0\&.0)"
.br
.in -1c
.SS "Private 속성"

.in +1c
.ti -1c
.RI "char * \fB_appName\fP"
.br
.ti -1c
.RI "char \fB_fileName\fP [MAX_PATH]"
.br
.in -1c
.SH "상세한 설명"
.PP 
Ini\&.h 파일의 10 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "CIni::CIni (const char * fileName)"

.PP
Ini\&.cpp 파일의 9 번째 라인에서 정의되었습니다\&.
.PP
.nf
10 {
11     _appName = "Property";
12 
13     ::GetCurrentDirectory(MAX_PATH, _fileName);
14     _tcscat(_fileName, "\\");
15     _tcscat(_fileName, fileName);
16     
17     //strncpy (_fileName, fileName, MAX_PATH);
18 }
.fi
.SS "CIni::~CIni ()\fC [virtual]\fP"

.PP
Ini\&.cpp 파일의 20 번째 라인에서 정의되었습니다\&.
.PP
.nf
21 {
22 }
.fi
.SH "멤버 함수 문서화"
.PP 
.SS "float CIni::LoadFloat (const char * keyName, float defaultValue = \fC0\&.0\fP)"

.PP
Ini\&.cpp 파일의 53 번째 라인에서 정의되었습니다\&.
.PP
.nf
54 {
55     char defaultString[64];
56     _snprintf (defaultString, 64, "%g", defaultValue);
57 
58     char returnedString[128] = "";
59     GetPrivateProfileString(_appName, keyName, defaultString, returnedString, sizeof(returnedString), _fileName);   
60     return (float)atof (returnedString);
61 }
.fi
.SS "int CIni::LoadInt (const char * keyName, int defaultValue = \fC0\fP)"

.PP
Ini\&.cpp 파일의 48 번째 라인에서 정의되었습니다\&.
.PP
.nf
49 {
50     return GetPrivateProfileInt(_appName, keyName, defaultValue, _fileName);
51 }
.fi
.SS "void CIni::LoadString (const char * keyName, char * returnedString, \fBDWORD\fP nSize, char * defaultValue = \fC''\fP)"

.PP
Ini\&.cpp 파일의 43 번째 라인에서 정의되었습니다\&.
.PP
.nf
44 {
45     GetPrivateProfileString(_appName, keyName, defaultValue, returnedString, nSize, _fileName); 
46 }
.fi
.SS "void CIni::SaveFloat (const char * keyName, float floatData)"

.PP
Ini\&.cpp 파일의 36 번째 라인에서 정의되었습니다\&.
.PP
.nf
37 {
38     char strData[64+10];
39     _snprintf (strData, 64, "%g", floatData);
40     WritePrivateProfileString(_appName, keyName, strData, _fileName);
41 }
.fi
.SS "void CIni::SaveInt (const char * keyName, int intData)"

.PP
Ini\&.cpp 파일의 29 번째 라인에서 정의되었습니다\&.
.PP
.nf
30 {
31     char strData[32+10];
32     _snprintf (strData, 32, "%d", intData);
33     WritePrivateProfileString(_appName, keyName, strData, _fileName);
34 }
.fi
.SS "void CIni::SaveString (const char * keyName, char * strData)"

.PP
Ini\&.cpp 파일의 24 번째 라인에서 정의되었습니다\&.
.PP
.nf
25 {
26     WritePrivateProfileString(_appName, keyName, strData, _fileName);
27 }
.fi
.SS "void CIni::Transfer (bool bSave, const char * keyName, char * strData, \fBDWORD\fP nSize, char * defaultData = \fC''\fP)"

.PP
Ini\&.cpp 파일의 63 번째 라인에서 정의되었습니다\&.
.PP
.nf
64 {
65     if (bSave) SaveString (keyName, strData);
66     else       LoadString (keyName, strData, nSize, defaultData);
67 }
.fi
.SS "void CIni::Transfer (bool bSave, const char * keyName, bool & boolData, bool defaultData = \fCfalse\fP)"

.PP
Ini\&.cpp 파일의 69 번째 라인에서 정의되었습니다\&.
.PP
.nf
70 {
71     if (bSave) SaveInt (keyName, boolData ? 1 : 0);
72     else       boolData = LoadInt (keyName, defaultData) ? true : false;
73 }
.fi
.SS "void CIni::Transfer (bool bSave, const char * keyName, int & intData, int defaultData = \fC0\fP)"

.PP
Ini\&.cpp 파일의 75 번째 라인에서 정의되었습니다\&.
.PP
.nf
76 {
77     if (bSave) SaveInt (keyName, intData);
78     else       intData = LoadInt (keyName, defaultData);
79 }
.fi
.SS "void CIni::Transfer (bool bSave, const char * keyName, long & longData, long defaultData = \fC0\fP)"

.PP
Ini\&.cpp 파일의 81 번째 라인에서 정의되었습니다\&.
.PP
.nf
82 {
83     if (bSave) SaveInt (keyName, (int)longData);
84     else       longData = (int)LoadInt (keyName, (int)defaultData);
85 }
.fi
.SS "void CIni::Transfer (bool bSave, const char * keyName, \fBDWORD\fP & dwordData, \fBDWORD\fP defaultData = \fC0\fP)"

.PP
Ini\&.cpp 파일의 87 번째 라인에서 정의되었습니다\&.
.PP
.nf
88 {
89     if (bSave) SaveInt (keyName, (int)dwordData);
90     else       dwordData = (int)LoadInt (keyName, (int)defaultData);
91 }
.fi
.SS "void CIni::Transfer (bool bSave, const char * keyName, float & floatData, float defaultData = \fC0\&.0f\fP)"

.PP
Ini\&.cpp 파일의 93 번째 라인에서 정의되었습니다\&.
.PP
.nf
94 {
95     if (bSave) SaveFloat (keyName, floatData);
96     else       floatData = LoadFloat (keyName, defaultData);
97 }
.fi
.SS "void CIni::Transfer (bool bSave, const char * keyName, double & doubleData, double defaultData = \fC0\&.0\fP)"

.PP
Ini\&.cpp 파일의 99 번째 라인에서 정의되었습니다\&.
.PP
.nf
100 {
101     if (bSave) SaveFloat (keyName, (float)doubleData);
102     else       doubleData = (float)LoadFloat (keyName, (float)defaultData);
103 }
.fi
.SH "멤버 데이타 문서화"
.PP 
.SS "char* CIni::_appName\fC [private]\fP"

.PP
Ini\&.h 파일의 36 번째 라인에서 정의되었습니다\&.
.SS "char CIni::_fileName[MAX_PATH]\fC [private]\fP"

.PP
Ini\&.h 파일의 37 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
