.TH "CScrollEdit" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CScrollEdit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScrollEdit\&.h>\fP
.PP
CEdit를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCScrollEdit\fP ()"
.br
.ti -1c
.RI "void \fBSetWindowText\fP (LPCTSTR lpszString)"
.br
.ti -1c
.RI "virtual \fB~CScrollEdit\fP ()"
.br
.in -1c
.SS "Protected 멤버 함수"

.in +1c
.ti -1c
.RI "virtual BOOL \fBPreCreateWindow\fP (CREATESTRUCT &cs)"
.br
.ti -1c
.RI "afx_msg void \fBOnChar\fP (\fBUINT\fP nChar, \fBUINT\fP nRepCnt, \fBUINT\fP nFlags)"
.br
.ti -1c
.RI "afx_msg LRESULT \fBOnCheckText\fP (WPARAM wParam, LPARAM lParam)"
.br
.ti -1c
.RI "void \fBShowHorizScrollBar\fP (BOOL bShow=TRUE)"
.br
.ti -1c
.RI "void \fBShowVertScrollBar\fP (BOOL bShow=TRUE)"
.br
.ti -1c
.RI "void \fBCheckScrolling\fP (LPCTSTR lpszString)"
.br
.in -1c
.SS "Private 속성"

.in +1c
.ti -1c
.RI "BOOL \fBm_bShowHoriz\fP"
.br
.ti -1c
.RI "BOOL \fBm_bShowVert\fP"
.br
.in -1c
.SS "정적 Private 속성"

.in +1c
.ti -1c
.RI "static const \fBUINT\fP \fBUWM_CHECKTEXT\fP = ::RegisterWindowMessage(\fBUWM_CHECKTEXT_MSG\fP)"
.br
.in -1c
.SH "상세한 설명"
.PP 
ScrollEdit\&.h 파일의 14 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "CScrollEdit::CScrollEdit ()"

.PP
ScrollEdit\&.cpp 파일의 23 번째 라인에서 정의되었습니다\&.
.PP
.nf
23                          : m_bShowHoriz(TRUE), m_bShowVert(TRUE)
24 {
25 }
.fi
.SS "CScrollEdit::~CScrollEdit ()\fC [virtual]\fP"

.PP
ScrollEdit\&.cpp 파일의 27 번째 라인에서 정의되었습니다\&.
.PP
.nf
28 {
29 }
.fi
.SH "멤버 함수 문서화"
.PP 
.SS "void CScrollEdit::CheckScrolling (LPCTSTR lpszString)\fC [protected]\fP"

.PP
ScrollEdit\&.cpp 파일의 31 번째 라인에서 정의되었습니다\&.
.PP
.nf
32 {
33     CRect oRect;
34     GetClientRect(&oRect);
35     CClientDC oDC(this);
36     int iHeight=0;
37     BOOL bHoriz = FALSE;
38     CFont* pEdtFont = GetFont();
39     if(pEdtFont != NULL)
40     {
41         //Determine Text Width and Height
42         SIZE oSize;
43         CFont* pOldFont = oDC\&.SelectObject(pEdtFont);
44         //Determine the line Height
45         oSize = oDC\&.GetTextExtent(CString(_T(" ")));
46         iHeight = oSize\&.cy;
47         //Text Width
48         int iWidth=0, i =0;
49         CString oStr;
50         //Parse the string, the lines in a multiline Edit are separated by "\r\n"
51         while(TRUE == ::AfxExtractSubString(oStr, lpszString, i, _T('\n')))
52         {
53             if(FALSE == bHoriz)
54             {
55                 int iLen = oStr\&.GetLength()-1;
56                 if(iLen >=0)
57                 {
58                     //Eliminate last '\r'
59                     if(_T('\r') == oStr\&.GetAt(iLen))
60                         oStr = oStr\&.Left(iLen);
61                     oSize = oDC\&.GetTextExtent(oStr);
62                     if(iWidth < oSize\&.cx)
63                         iWidth = oSize\&.cx;
64                     if(iWidth >= oRect\&.Width())
65                         bHoriz = TRUE;
66                 }
67             }
68             i++;
69         }
70         oDC\&.SelectObject(pOldFont);
71         //Text Height
72         iHeight *= i;
73     }
74     ShowHorizScrollBar(bHoriz);
75     ShowVertScrollBar(iHeight >= oRect\&.Height());
76 }
.fi
.SS "void CScrollEdit::OnChar (\fBUINT\fP nChar, \fBUINT\fP nRepCnt, \fBUINT\fP nFlags)\fC [protected]\fP"

.PP
ScrollEdit\&.cpp 파일의 102 번째 라인에서 정의되었습니다\&.
.PP
.nf
103 {
104     //Possible Text Change
105     PostMessage(UWM_CHECKTEXT);
106     CEdit::OnChar(nChar, nRepCnt, nFlags);
107 }
.fi
.SS "LRESULT CScrollEdit::OnCheckText (WPARAM wParam, LPARAM lParam)\fC [protected]\fP"

.PP
ScrollEdit\&.cpp 파일의 109 번째 라인에서 정의되었습니다\&.
.PP
.nf
110 {
111     CString oStr;
112     GetWindowText(oStr);
113     CheckScrolling(oStr);
114     return 0;
115 }
.fi
.SS "BOOL CScrollEdit::PreCreateWindow (CREATESTRUCT & cs)\fC [protected]\fP, \fC [virtual]\fP"

.PP
ScrollEdit\&.cpp 파일의 95 번째 라인에서 정의되었습니다\&.
.PP
.nf
96 {
97     //Add WS_HSCROLL, WS_VSCROLL, ES_MULTILINE, ES_AUTOHSCROLL, ES_AUTOVSCROLL
98     cs\&.style |= (WS_HSCROLL|WS_VSCROLL|ES_MULTILINE|ES_AUTOHSCROLL|ES_AUTOVSCROLL);
99     return CEdit::PreCreateWindow(cs);
100 }
.fi
.SS "void CScrollEdit::SetWindowText (LPCTSTR lpszString)"

.PP
ScrollEdit\&.cpp 파일의 79 번째 라인에서 정의되었습니다\&.
.PP
.nf
80 {
81     CheckScrolling(lpszString);
82     CEdit::SetWindowText(lpszString);
83 }
.fi
.SS "void CScrollEdit::ShowHorizScrollBar (BOOL bShow = \fCTRUE\fP)\fC [inline]\fP, \fC [protected]\fP"

.PP
ScrollEdit\&.h 파일의 61 번째 라인에서 정의되었습니다\&.
.PP
.nf
62 {
63     if(m_bShowHoriz != bShow)
64     {
65         ShowScrollBar(SB_HORZ, bShow);
66         m_bShowHoriz = bShow;
67     }
68 }
.fi
.SS "void CScrollEdit::ShowVertScrollBar (BOOL bShow = \fCTRUE\fP)\fC [inline]\fP, \fC [protected]\fP"

.PP
ScrollEdit\&.h 파일의 70 번째 라인에서 정의되었습니다\&.
.PP
.nf
71 {
72     if(m_bShowVert != bShow)
73     {
74         ShowScrollBar(SB_VERT, bShow);
75         m_bShowVert = bShow;
76     }
77 }
.fi
.SH "멤버 데이타 문서화"
.PP 
.SS "BOOL CScrollEdit::m_bShowHoriz\fC [private]\fP"

.PP
ScrollEdit\&.h 파일의 55 번째 라인에서 정의되었습니다\&.
.SS "BOOL CScrollEdit::m_bShowVert\fC [private]\fP"

.PP
ScrollEdit\&.h 파일의 56 번째 라인에서 정의되었습니다\&.
.SS "const \fBUINT\fP CScrollEdit::UWM_CHECKTEXT = ::RegisterWindowMessage(\fBUWM_CHECKTEXT_MSG\fP)\fC [static]\fP, \fC [private]\fP"

.PP
ScrollEdit\&.h 파일의 53 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
