.TH "DXF_ENTITY_ITEM" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXF_ENTITY_ITEM \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dxf_parse\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "\fBeEntityType\fP \fBtype\fP"
.br
.ti -1c
.RI "double \fBx0\fP"
.br
.ti -1c
.RI "double \fBy0\fP"
.br
.ti -1c
.RI "double \fBz0\fP"
.br
.ti -1c
.RI "double \fBx1\fP"
.br
.ti -1c
.RI "double \fBy1\fP"
.br
.ti -1c
.RI "double \fBz1\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
dxf_parse\&.h 파일의 14 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이타 문서화"
.PP 
.SS "\fBeEntityType\fP DXF_ENTITY_ITEM::type"

.PP
dxf_parse\&.h 파일의 15 번째 라인에서 정의되었습니다\&.
.SS "double DXF_ENTITY_ITEM::x0"

.PP
dxf_parse\&.h 파일의 16 번째 라인에서 정의되었습니다\&.
.SS "double DXF_ENTITY_ITEM::x1"

.PP
dxf_parse\&.h 파일의 17 번째 라인에서 정의되었습니다\&.
.SS "double DXF_ENTITY_ITEM::y0"

.PP
dxf_parse\&.h 파일의 16 번째 라인에서 정의되었습니다\&.
.SS "double DXF_ENTITY_ITEM::y1"

.PP
dxf_parse\&.h 파일의 17 번째 라인에서 정의되었습니다\&.
.SS "double DXF_ENTITY_ITEM::z0"

.PP
dxf_parse\&.h 파일의 16 번째 라인에서 정의되었습니다\&.
.SS "double DXF_ENTITY_ITEM::z1"

.PP
dxf_parse\&.h 파일의 17 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
