.TH "D:/RobotSimulator/test/robot_society/robot society beta/Common/MultimediaTimer.h" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/Common/MultimediaTimer.h \- 
.SH SYNOPSIS
.br
.PP
.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBCMultimediaTimer\fP"
.br
.in -1c
.SS "타입정의"

.in +1c
.ti -1c
.RI "typedef unsigned long \fBDWORD\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUINT\fP"
.br
.in -1c
.SH "타입정의 문서화"
.PP 
.SS "typedef unsigned long \fBDWORD\fP"

.PP
MultimediaTimer\&.h 파일의 14 번째 라인에서 정의되었습니다\&.
.SS "typedef unsigned int \fBUINT\fP"

.PP
MultimediaTimer\&.h 파일의 15 번째 라인에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
