.TH "D:/RobotSimulator/test/robot_society/robot society beta/parameters.h" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/parameters.h \- 
.SH SYNOPSIS
.br
.PP
.SS "매크로"

.in +1c
.ti -1c
.RI "#define \fBSTAGE_WIDTH\fP   700"
.br
.ti -1c
.RI "#define \fBSTAGE_HEIGHT\fP   400"
.br
.ti -1c
.RI "#define \fBPI\fP   (double)3\&.141592"
.br
.ti -1c
.RI "#define \fBpi\fP   (double)3\&.141592"
.br
.ti -1c
.RI "#define \fBD2R\fP   (double)\fBPI\fP/180"
.br
.ti -1c
.RI "#define \fBR2D\fP   (double)180/\fBPI\fP"
.br
.ti -1c
.RI "#define \fBCOLOR_L_BROWN\fP   RGB(0x99,0x66,0x33)"
.br
.ti -1c
.RI "#define \fBCOLOR_D_BROWN\fP   RGB(0x66,0x33,0x00)"
.br
.ti -1c
.RI "#define \fBCOLOR_L_PURPLE\fP   RGB(0xCC,0x66,0xCC)"
.br
.ti -1c
.RI "#define \fBCOLOR_D_PURPLE\fP   RGB(0x99,0x33,0x99)"
.br
.ti -1c
.RI "#define \fBCOLOR_L_GREEN\fP   RGB(0x99,0xFF,0x99)"
.br
.ti -1c
.RI "#define \fBCOLOR_D_GREEN\fP   RGB(0x33,0xCC,0x33)"
.br
.ti -1c
.RI "#define \fBCOLOR_L_RED\fP   RGB(0xFF,0x66,0x66)"
.br
.ti -1c
.RI "#define \fBCOLOR_D_RED\fP   RGB(0xCC,0x11,0x11)"
.br
.ti -1c
.RI "#define \fBCOLOR_L_BLUE\fP   RGB(0x33,0x33,0xFF)"
.br
.ti -1c
.RI "#define \fBCOLOR_D_BLUE\fP   RGB(0x00,0x00,0xFF)"
.br
.ti -1c
.RI "#define \fBCOLOR_L_BLACK\fP   RGB(0x99,0x99,0x99)"
.br
.ti -1c
.RI "#define \fBCOLOR_D_BLACK\fP   RGB(0x00,0x00,0x00)"
.br
.ti -1c
.RI "#define \fBCOLOR_WHITE\fP   RGB(0xFF,0xFF,0xFF)"
.br
.ti -1c
.RI "#define \fBPASTEL_LL_BROWN\fP   RGB(0xFF,0xE5,0xCB)"
.br
.ti -1c
.RI "#define \fBPASTEL_DD_BROWN\fP   RGB(0x8B,0x63,0x31)"
.br
.ti -1c
.RI "#define \fBPASTEL_PINK\fP   RGB(0xFF,0x6E,0x6E)"
.br
.ti -1c
.RI "#define \fBPASTEL_PINKBROWN\fP   RGB(0xC8,0x64,0x64)"
.br
.ti -1c
.RI "#define \fBdarkorchid\fP   RGB(0x99,0x32,0xCC)"
.br
.ti -1c
.RI "#define \fBdarkviolet\fP   RGB(0x94,0x00,0xD3)"
.br
.ti -1c
.RI "#define \fBblueviolet\fP   RGB(0x8A,0x2B,0xE2)"
.br
.ti -1c
.RI "#define \fBmediumblueviolet\fP   RGB(0xDA,0xAB,0xFF)"
.br
.ti -1c
.RI "#define \fBmediumorchid\fP   RGB(0xBA,0x55,0xD3)"
.br
.ti -1c
.RI "#define \fBplum\fP   RGB(0xDD,0xA0,0xDD)"
.br
.ti -1c
.RI "#define \fBdarkgreen\fP   RGB(0x00,0x64,0x00)"
.br
.ti -1c
.RI "#define \fBgreen\fP   RGB(0x00,0x80,0x00)"
.br
.ti -1c
.RI "#define \fBseagreen\fP   RGB(0x2E,0x8B,0x57)"
.br
.ti -1c
.RI "#define \fBmediumseegreen\fP   RGB(0x3C,0xB3,0x71)"
.br
.in -1c
.SH "매크로 문서화"
.PP 
.SS "#define blueviolet   RGB(0x8A,0x2B,0xE2)"

.PP
parameters\&.h 파일의 37 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_D_BLACK   RGB(0x00,0x00,0x00)"

.PP
parameters\&.h 파일의 28 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_D_BLUE   RGB(0x00,0x00,0xFF)"

.PP
parameters\&.h 파일의 26 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_D_BROWN   RGB(0x66,0x33,0x00)"

.PP
parameters\&.h 파일의 18 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_D_GREEN   RGB(0x33,0xCC,0x33)"

.PP
parameters\&.h 파일의 22 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_D_PURPLE   RGB(0x99,0x33,0x99)"

.PP
parameters\&.h 파일의 20 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_D_RED   RGB(0xCC,0x11,0x11)"

.PP
parameters\&.h 파일의 24 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_L_BLACK   RGB(0x99,0x99,0x99)"

.PP
parameters\&.h 파일의 27 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_L_BLUE   RGB(0x33,0x33,0xFF)"

.PP
parameters\&.h 파일의 25 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_L_BROWN   RGB(0x99,0x66,0x33)"

.PP
parameters\&.h 파일의 17 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_L_GREEN   RGB(0x99,0xFF,0x99)"

.PP
parameters\&.h 파일의 21 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_L_PURPLE   RGB(0xCC,0x66,0xCC)"

.PP
parameters\&.h 파일의 19 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_L_RED   RGB(0xFF,0x66,0x66)"

.PP
parameters\&.h 파일의 23 번째 라인에서 정의되었습니다\&.
.SS "#define COLOR_WHITE   RGB(0xFF,0xFF,0xFF)"

.PP
parameters\&.h 파일의 29 번째 라인에서 정의되었습니다\&.
.SS "#define D2R   (double)\fBPI\fP/180"

.PP
parameters\&.h 파일의 10 번째 라인에서 정의되었습니다\&.
.SS "#define darkgreen   RGB(0x00,0x64,0x00)"

.PP
parameters\&.h 파일의 41 번째 라인에서 정의되었습니다\&.
.SS "#define darkorchid   RGB(0x99,0x32,0xCC)"

.PP
parameters\&.h 파일의 35 번째 라인에서 정의되었습니다\&.
.SS "#define darkviolet   RGB(0x94,0x00,0xD3)"

.PP
parameters\&.h 파일의 36 번째 라인에서 정의되었습니다\&.
.SS "#define green   RGB(0x00,0x80,0x00)"

.PP
parameters\&.h 파일의 42 번째 라인에서 정의되었습니다\&.
.SS "#define mediumblueviolet   RGB(0xDA,0xAB,0xFF)"

.PP
parameters\&.h 파일의 38 번째 라인에서 정의되었습니다\&.
.SS "#define mediumorchid   RGB(0xBA,0x55,0xD3)"

.PP
parameters\&.h 파일의 39 번째 라인에서 정의되었습니다\&.
.SS "#define mediumseegreen   RGB(0x3C,0xB3,0x71)"

.PP
parameters\&.h 파일의 44 번째 라인에서 정의되었습니다\&.
.SS "#define PASTEL_DD_BROWN   RGB(0x8B,0x63,0x31)"

.PP
parameters\&.h 파일의 32 번째 라인에서 정의되었습니다\&.
.SS "#define PASTEL_LL_BROWN   RGB(0xFF,0xE5,0xCB)"

.PP
parameters\&.h 파일의 31 번째 라인에서 정의되었습니다\&.
.SS "#define PASTEL_PINK   RGB(0xFF,0x6E,0x6E)"

.PP
parameters\&.h 파일의 33 번째 라인에서 정의되었습니다\&.
.SS "#define PASTEL_PINKBROWN   RGB(0xC8,0x64,0x64)"

.PP
parameters\&.h 파일의 34 번째 라인에서 정의되었습니다\&.
.SS "#define PI   (double)3\&.141592"

.PP
parameters\&.h 파일의 7 번째 라인에서 정의되었습니다\&.
.SS "#define pi   (double)3\&.141592"

.PP
parameters\&.h 파일의 8 번째 라인에서 정의되었습니다\&.
.SS "#define plum   RGB(0xDD,0xA0,0xDD)"

.PP
parameters\&.h 파일의 40 번째 라인에서 정의되었습니다\&.
.SS "#define R2D   (double)180/\fBPI\fP"

.PP
parameters\&.h 파일의 11 번째 라인에서 정의되었습니다\&.
.SS "#define seagreen   RGB(0x2E,0x8B,0x57)"

.PP
parameters\&.h 파일의 43 번째 라인에서 정의되었습니다\&.
.SS "#define STAGE_HEIGHT   400"

.PP
parameters\&.h 파일의 5 번째 라인에서 정의되었습니다\&.
.SS "#define STAGE_WIDTH   700"

.PP
parameters\&.h 파일의 4 번째 라인에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
