.TH "PUPPET" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PUPPET \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robot object\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBPUPPET\fP (void)"
.br
.ti -1c
.RI "\fB~PUPPET\fP (void)"
.br
.ti -1c
.RI "void \fBCopy\fP (\fBPUPPET\fP fr)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "bool \fBisMeet\fP (\fBPUPPET\fP *p)"
.br
.ti -1c
.RI "bool \fBisMeet\fP (CPoint p)"
.br
.ti -1c
.RI "void \fBSetV\fP (double v_in)"
.br
.ti -1c
.RI "void \fBSetW\fP (double w_in)"
.br
.in -1c
.SS "Public 속성"

.in +1c
.ti -1c
.RI "CPoint \fBpoint\fP"
.br
.ti -1c
.RI "double \fBtheta\fP"
.br
.ti -1c
.RI "double \fBv\fP"
.br
.ti -1c
.RI "double \fBw\fP"
.br
.ti -1c
.RI "double \fBbody_radius\fP"
.br
.ti -1c
.RI "double \fBhead_radius\fP"
.br
.ti -1c
.RI "double \fBneck_length\fP"
.br
.ti -1c
.RI "\fBRGB_DATA\fP \fBhead_color\fP"
.br
.ti -1c
.RI "\fBRGB_DATA\fP \fBbody_color\fP"
.br
.ti -1c
.RI "\fBCHARACTOR\fP \fBch\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
robot object\&.h 파일의 49 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "PUPPET::PUPPET (void)"

.PP
robot object\&.cpp 파일의 6 번째 라인에서 정의되었습니다\&.
.PP
.nf
7 {
8     this->Reset();
9 }
.fi
.SS "PUPPET::~PUPPET (void)"

.PP
robot object\&.cpp 파일의 11 번째 라인에서 정의되었습니다\&.
.PP
.nf
12 {
13 }
.fi
.SH "멤버 함수 문서화"
.PP 
.SS "void PUPPET::Copy (\fBPUPPET\fP fr)"

.PP
robot object\&.cpp 파일의 15 번째 라인에서 정의되었습니다\&.
.PP
.nf
16 {
17     this->point\&.x    = fr\&.point\&.x;
18     this->point\&.y    = fr\&.point\&.y;
19     this->theta     = fr\&.theta;
20 
21     this->body_radius = fr\&.body_radius;
22     this->head_radius = fr\&.head_radius;
23     this->neck_length = fr\&.neck_length;
24 
25     this->w     = fr\&.w;
26     this->v     = fr\&.v;
27     
28     this->body_color\&.R   = fr\&.body_color\&.R;
29     this->body_color\&.G   = fr\&.body_color\&.G;
30     this->body_color\&.B   = fr\&.body_color\&.B;
31 
32     this->head_color\&.R   = fr\&.head_color\&.R;
33     this->head_color\&.G   = fr\&.head_color\&.G;
34     this->head_color\&.B   = fr\&.head_color\&.B;
35 }
.fi
.SS "bool PUPPET::isMeet (\fBPUPPET\fP * p)"

.PP
robot object\&.cpp 파일의 65 번째 라인에서 정의되었습니다\&.
.PP
.nf
66 {
67     if( Get_Length(this->point, p->point) < (this->body_radius + p->body_radius))
68     {//두 점 사이의 거리가 반지름의 합보다 짧으면 만난 것이다\&. 
69         return TRUE;
70     }
71     else
72     {
73         return FALSE;
74     }
75 }
.fi
.SS "bool PUPPET::isMeet (CPoint p)"

.PP
robot object\&.cpp 파일의 77 번째 라인에서 정의되었습니다\&.
.PP
.nf
78 {
79     if( Get_Length(this->point, p) < this->body_radius )
80     {//두 점 사이의 거리가 반지름의 합보다 짧으면 만난 것이다\&. 
81         return TRUE;
82     }
83     else
84     {
85         return FALSE;
86     }
87 }
.fi
.SS "void PUPPET::Reset ()"

.PP
robot object\&.cpp 파일의 37 번째 라인에서 정의되었습니다\&.
.PP
.nf
38 {
39     point\&.x = 0;
40     point\&.y = 0;
41     theta = 0;
42 
43     v = 0;
44     w = 0;
45 
46     body_radius = ROBOT_RADIUS;
47     head_radius = HEAD_RADIUS;
48     neck_length = NECK_LENGTH;
49 
50     body_color\&.R = rand() % 256;
51     body_color\&.G = rand() % 256;
52     body_color\&.B = rand() % 256;
53 
54     head_color\&.R = rand() % 256;
55     head_color\&.G = rand() % 256;
56     head_color\&.B = rand() % 256;
57 
58     ch\&.etc       = IDLE;
59     ch\&.level = IDLE;
60     ch\&.main      = IDLE;
61     ch\&.sub       = IDLE;
62     ch\&.type      = IDLE;
63 }
.fi
.SS "void PUPPET::SetV (double v_in)"

.PP
robot object\&.cpp 파일의 90 번째 라인에서 정의되었습니다\&.
.PP
.nf
91 {
92     v = v_in;
93     if(v >= V_MAX)  v = V_MAX;
94     if(v <= -V_MAX) v = -V_MAX;
95 
96     
97 }
.fi
.SS "void PUPPET::SetW (double w_in)"

.PP
robot object\&.cpp 파일의 99 번째 라인에서 정의되었습니다\&.
.PP
.nf
100 {
101     w = w_in;
102     if(w >= W_MAX)  w = W_MAX;
103     if(w <= -W_MAX) w = -W_MAX;
104 
105 }
.fi
.SH "멤버 데이타 문서화"
.PP 
.SS "\fBRGB_DATA\fP PUPPET::body_color"

.PP
robot object\&.h 파일의 73 번째 라인에서 정의되었습니다\&.
.SS "double PUPPET::body_radius"

.PP
robot object\&.h 파일의 68 번째 라인에서 정의되었습니다\&.
.SS "\fBCHARACTOR\fP PUPPET::ch"

.PP
robot object\&.h 파일의 76 번째 라인에서 정의되었습니다\&.
.SS "\fBRGB_DATA\fP PUPPET::head_color"

.PP
robot object\&.h 파일의 72 번째 라인에서 정의되었습니다\&.
.SS "double PUPPET::head_radius"

.PP
robot object\&.h 파일의 69 번째 라인에서 정의되었습니다\&.
.SS "double PUPPET::neck_length"

.PP
robot object\&.h 파일의 70 번째 라인에서 정의되었습니다\&.
.SS "CPoint PUPPET::point"

.PP
robot object\&.h 파일의 64 번째 라인에서 정의되었습니다\&.
.SS "double PUPPET::theta"

.PP
robot object\&.h 파일의 65 번째 라인에서 정의되었습니다\&.
.SS "double PUPPET::v"

.PP
robot object\&.h 파일의 66 번째 라인에서 정의되었습니다\&.
.SS "double PUPPET::w"

.PP
robot object\&.h 파일의 66 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
