.TH "D:/RobotSimulator/test/robot_society/robot society beta/resource.h" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/resource.h \- 
.SH SYNOPSIS
.br
.PP
.SS "매크로"

.in +1c
.ti -1c
.RI "#define \fBIDM_ABOUTBOX\fP   0x0010"
.br
.ti -1c
.RI "#define \fBIDD_ABOUTBOX\fP   100"
.br
.ti -1c
.RI "#define \fBIDS_ABOUTBOX\fP   101"
.br
.ti -1c
.RI "#define \fBIDD_ROBOTSOCIETYBETA_DIALOG\fP   102"
.br
.ti -1c
.RI "#define \fBIDR_MAINFRAME\fP   128"
.br
.ti -1c
.RI "#define \fBIDR_MENU1\fP   129"
.br
.ti -1c
.RI "#define \fBIDD_STATUS_DIALOG\fP   130"
.br
.ti -1c
.RI "#define \fBIDC_STATIC_STAGE1\fP   1001"
.br
.ti -1c
.RI "#define \fBIDB_START_STOP\fP   1002"
.br
.ti -1c
.RI "#define \fBIDB_RESET\fP   1003"
.br
.ti -1c
.RI "#define \fBIDC_SLIDER_SPEED\fP   1004"
.br
.ti -1c
.RI "#define \fBIDB_OPEN_STATUS\fP   1005"
.br
.ti -1c
.RI "#define \fBIDC_EDIT_ROBOT_NUM\fP   1005"
.br
.ti -1c
.RI "#define \fBIDC_CHECK_SHOW_STATUS\fP   1007"
.br
.ti -1c
.RI "#define \fBIDC_EDIT1\fP   1009"
.br
.ti -1c
.RI "#define \fBIDC_EDIT2\fP   1010"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON1\fP   1010"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON_LOAD_MAP\fP   1010"
.br
.ti -1c
.RI "#define \fBIDM_OPEN\fP   32771"
.br
.ti -1c
.RI "#define \fBIDM_SAVE\fP   32772"
.br
.in -1c
.SH "매크로 문서화"
.PP 
.SS "#define IDB_OPEN_STATUS   1005"

.PP
resource\&.h 파일의 16 번째 라인에서 정의되었습니다\&.
.SS "#define IDB_RESET   1003"

.PP
resource\&.h 파일의 14 번째 라인에서 정의되었습니다\&.
.SS "#define IDB_START_STOP   1002"

.PP
resource\&.h 파일의 13 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_BUTTON1   1010"

.PP
resource\&.h 파일의 21 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_BUTTON_LOAD_MAP   1010"

.PP
resource\&.h 파일의 22 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_CHECK_SHOW_STATUS   1007"

.PP
resource\&.h 파일의 18 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_EDIT1   1009"

.PP
resource\&.h 파일의 19 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_EDIT2   1010"

.PP
resource\&.h 파일의 20 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_EDIT_ROBOT_NUM   1005"

.PP
resource\&.h 파일의 17 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_SLIDER_SPEED   1004"

.PP
resource\&.h 파일의 15 번째 라인에서 정의되었습니다\&.
.SS "#define IDC_STATIC_STAGE1   1001"

.PP
resource\&.h 파일의 12 번째 라인에서 정의되었습니다\&.
.SS "#define IDD_ABOUTBOX   100"

.PP
resource\&.h 파일의 6 번째 라인에서 정의되었습니다\&.
.SS "#define IDD_ROBOTSOCIETYBETA_DIALOG   102"

.PP
resource\&.h 파일의 8 번째 라인에서 정의되었습니다\&.
.SS "#define IDD_STATUS_DIALOG   130"

.PP
resource\&.h 파일의 11 번째 라인에서 정의되었습니다\&.
.SS "#define IDM_ABOUTBOX   0x0010"

.PP
resource\&.h 파일의 5 번째 라인에서 정의되었습니다\&.
.SS "#define IDM_OPEN   32771"

.PP
resource\&.h 파일의 23 번째 라인에서 정의되었습니다\&.
.SS "#define IDM_SAVE   32772"

.PP
resource\&.h 파일의 24 번째 라인에서 정의되었습니다\&.
.SS "#define IDR_MAINFRAME   128"

.PP
resource\&.h 파일의 9 번째 라인에서 정의되었습니다\&.
.SS "#define IDR_MENU1   129"

.PP
resource\&.h 파일의 10 번째 라인에서 정의되었습니다\&.
.SS "#define IDS_ABOUTBOX   101"

.PP
resource\&.h 파일의 7 번째 라인에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
