.TH "D:/RobotSimulator/test/robot_society/robot society beta/robot object.h" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/robot object.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'parameters\&.h'\fP
.br
\fC#include 'basic_function\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "struct \fBtRGB_DATA\fP"
.br
.ti -1c
.RI "struct \fBCHARACTOR\fP"
.br
.ti -1c
.RI "class \fBPUPPET\fP"
.br
.ti -1c
.RI "class \fBROBOT_OBJECTS\fP"
.br
.in -1c
.SS "매크로"

.in +1c
.ti -1c
.RI "#define \fBROBOT_RADIUS\fP   15"
.br
.ti -1c
.RI "#define \fBHEAD_RADIUS\fP   9"
.br
.ti -1c
.RI "#define \fBNECK_LENGTH\fP   -6"
.br
.ti -1c
.RI "#define \fBMAX_ROBOT_COUNT\fP   1000"
.br
.ti -1c
.RI "#define \fBMAX_STAGE_LENGTH\fP   2000"
.br
.ti -1c
.RI "#define \fBMAX_STAGE_HALF_LENGTH\fP   (\fBMAX_STAGE_LENGTH\fP/2)"
.br
.ti -1c
.RI "#define \fBV_MAX\fP   (double)30"
.br
.ti -1c
.RI "#define \fBW_MAX\fP   (double)0\&.04"
.br
.ti -1c
.RI "#define \fBIDLE\fP   0"
.br
.in -1c
.SS "타입정의"

.in +1c
.ti -1c
.RI "typedef struct \fBtRGB_DATA\fP \fBRGB_DATA\fP"
.br
.ti -1c
.RI "typedef struct \fBCHARACTOR\fP \fBCHARACTOR\fP"
.br
.in -1c
.SH "매크로 문서화"
.PP 
.SS "#define HEAD_RADIUS   9"

.PP
robot object\&.h 파일의 4 번째 라인에서 정의되었습니다\&.
.SS "#define IDLE   0"

.PP
robot object\&.h 파일의 16 번째 라인에서 정의되었습니다\&.
.SS "#define MAX_ROBOT_COUNT   1000"

.PP
robot object\&.h 파일의 7 번째 라인에서 정의되었습니다\&.
.SS "#define MAX_STAGE_HALF_LENGTH   (\fBMAX_STAGE_LENGTH\fP/2)"

.PP
robot object\&.h 파일의 10 번째 라인에서 정의되었습니다\&.
.SS "#define MAX_STAGE_LENGTH   2000"

.PP
robot object\&.h 파일의 9 번째 라인에서 정의되었습니다\&.
.SS "#define NECK_LENGTH   -6"

.PP
robot object\&.h 파일의 5 번째 라인에서 정의되었습니다\&.
.SS "#define ROBOT_RADIUS   15"

.PP
robot object\&.h 파일의 3 번째 라인에서 정의되었습니다\&.
.SS "#define V_MAX   (double)30"

.PP
robot object\&.h 파일의 12 번째 라인에서 정의되었습니다\&.
.SS "#define W_MAX   (double)0\&.04"

.PP
robot object\&.h 파일의 13 번째 라인에서 정의되었습니다\&.
.SH "타입정의 문서화"
.PP 
.SS "typedef struct \fBCHARACTOR\fP \fBCHARACTOR\fP"

.SS "typedef struct \fBtRGB_DATA\fP \fBRGB_DATA\fP"

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
