.TH "D:/RobotSimulator/test/robot_society/robot society beta/robot object.cpp" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/robot object.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'StdAfx\&.h'\fP
.br
\fC#include 'robot object\&.h'\fP
.br

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
