.TH "D:/RobotSimulator/test/robot_society/robot society beta/robot_status.h" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/robot_status.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'robot object\&.h'\fP
.br
\fC#include 'afxwin\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBROBOT_STATUS\fP"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
