.TH "D:/RobotSimulator/test/robot_society/robot society beta/robot society beta.cpp" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/robot society beta.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'robot society beta\&.h'\fP
.br
\fC#include 'robot society betaDlg\&.h'\fP
.br

.SS "변수"

.in +1c
.ti -1c
.RI "\fBCrobotsocietybetaApp\fP \fBtheApp\fP"
.br
.in -1c
.SH "변수 문서화"
.PP 
.SS "\fBCrobotsocietybetaApp\fP theApp"

.PP
robot society beta\&.cpp 파일의 31 번째 라인에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
