.TH "D:/RobotSimulator/test/robot_society/robot society beta/stdafx.h" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/RobotSimulator/test/robot_society/robot society beta/stdafx.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'targetver\&.h'\fP
.br
\fC#include <afxwin\&.h>\fP
.br
\fC#include <afxext\&.h>\fP
.br
\fC#include <afxdisp\&.h>\fP
.br
\fC#include <afxdtctl\&.h>\fP
.br
\fC#include <afxcmn\&.h>\fP
.br

.SS "매크로"

.in +1c
.ti -1c
.RI "#define \fB_SECURE_ATL\fP   1"
.br
.ti -1c
.RI "#define \fBVC_EXTRALEAN\fP"
.br
.ti -1c
.RI "#define \fB_ATL_CSTRING_EXPLICIT_CONSTRUCTORS\fP"
.br
.ti -1c
.RI "#define \fB_AFX_ALL_WARNINGS\fP"
.br
.in -1c
.SH "매크로 문서화"
.PP 
.SS "#define _AFX_ALL_WARNINGS"

.PP
stdafx\&.h 파일의 20 번째 라인에서 정의되었습니다\&.
.SS "#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS"

.PP
stdafx\&.h 파일의 17 번째 라인에서 정의되었습니다\&.
.SS "#define _SECURE_ATL   1"

.PP
stdafx\&.h 파일의 8 번째 라인에서 정의되었습니다\&.
.SS "#define VC_EXTRALEAN"

.PP
stdafx\&.h 파일의 12 번째 라인에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
