.TH "tRGB_DATA" 3 "화 1월 27 2015" "Version Ver 1.0.0" "Test" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tRGB_DATA \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robot object\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "unsigned char \fBR\fP"
.br
.ti -1c
.RI "unsigned char \fBG\fP"
.br
.ti -1c
.RI "unsigned char \fBB\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
robot object\&.h 파일의 33 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이타 문서화"
.PP 
.SS "unsigned char tRGB_DATA::B"

.PP
robot object\&.h 파일의 37 번째 라인에서 정의되었습니다\&.
.SS "unsigned char tRGB_DATA::G"

.PP
robot object\&.h 파일의 36 번째 라인에서 정의되었습니다\&.
.SS "unsigned char tRGB_DATA::R"

.PP
robot object\&.h 파일의 35 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Test를 위해 Doxygen에 의해 자동으로 생성됨\&.
